version: "3.8"
services:
  app:
    build:
      context: ./docker/php/ # The path of the Dockerfile
    volumes:
      - ".:/var/www/html"
      - "./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini"
    # uncomment this section to create database container
    # depends_on: 
    #   - mysql
    # end here
    working_dir: /var/www/html
    environment:
      SERVICE_NAME: k8s-app

      # uncomment this section to replace env in lumen
      # DB_PORT: 4306  
      # MYSQL_DATABASE: homestead
      # MYSQL_USER: homestead
      # MYSQL_PASSWORD: secret
      # MYSQL_ROOT_PASSWORD: secret
      # end here
    networks:
      - app_network

  nginx:
    build:
      context: ./docker/. # The path of the Dockerfile
    volumes:
    - "./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini"
    volumes_from:
    - app
    ports:
      - "8181:80"
    depends_on:
      - app
    networks:
      - app_network

  # mysql:
  #   image: mysql:5.7.22
  #   container_name: mysql
  #   tty: true
  #   command: --innodb_use_native_aio=0
  #   ports:
  #     - "4306:3306"
  #   volumes:
  #     - ./mysql:/var/lib/mysql
  #   environment: 
  #     MYSQL_DATABASE: homestead 
  #     MYSQL_USER: homestead
  #     MYSQL_PASSWORD: secret
  #     MYSQL_ROOT_PASSWORD: secret

networks:
  app_network:
    driver: bridge