version: '3.8'

services:

  php:
    build: .
    ports:
      - 8080:80
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      # - ./dockerize/vhost.conf:/etc/apache2/sites-available/000-default.conf 
    # links:
    #     - database
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  # database:
  #       image: mysql:5.7
  #       environment:
  #         - "MYSQL_ROOT_PASSWORD=common404"
  #         - "MYSQL_DATABASE=laravel"
  #       volumes:
  #         - ./db_data:/var/lib/mysql
  #       ports:
  #         - "33065:3306"

